services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: minutebound-b-backend
    env_file:
      - .env.backend 
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - minutebound-network
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: minutebound-b-elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - minutebound-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    container_name: minutebound-b-redis
    ports:
      - "6379:6379"
    networks:
      - minutebound-network
    restart: unless-stopped

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: minutebound-b-redis-insight
    ports:
      - "5540:5540"
    networks:
      - minutebound-network
    restart: unless-stopped
    depends_on:
      - redis

  postgres:
    image: postgres:15-alpine
    container_name: minutebound-b-postgres
    restart: always
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minutebound-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: minutebound-b-pgadmin
    restart: always
    env_file:
      - .env.pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - minutebound-network

networks:
  minutebound-network:
    name: minutebound-network 
    driver: bridge

volumes:
  es_data:
    driver: local
  postgres_data:
    driver: local